base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 600
  pool: 25
  username: root
  password: pwssord
  host: localhost
  port: 3306
  database: database_name

development:
  <<: *base

test:
  <<: *base

production:
  <<: *base
